platform :ios, '8.0'
target "tc" do
    use_frameworks!
    pod "FDStackView", "1.0"
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDWebImage', '~> 3.8.1'
    pod 'CocoaLumberjack'
    pod 'SwiftyJSON'
    pod 'CocoaAsyncSocket'

end
